CREATE TABLE EMPLOYEE (
    ID SERIAL PRIMARY KEY,
    LASTNAME TEXT,
    FIRSTNAME TEXT,
    MIDDLENAME TEXT,
    TABLENUM TEXT,
    SUBDIVISION TEXT,
    PROFESSION TEXT,
    SEX TEXT,
    CLOTHES TEXT,
    SHOES TEXT,
    HEADWEAR TEXT,
    GASMASK TEXT,
    RESPIRATOR TEXT,
    MITTENS TEXT,
    GLOVES TEXT    
);

CREATE TABLE STANDARTS (
    ID SERIAL PRIMARY KEY,
    EMPLOYEE_ID INTEGER REFERENCES EMPLOYEE(ID),
    NAME TEXT,
    POSITION TEXT,
    MEASURE TEXT,
    QUANTITY TEXT
);

CREATE TABLE EQIUPMENT (
    ID SERIAL PRIMARY KEY,
    EMPLOYEE_ID INTEGER REFERENCES EMPLOYEE(ID),
    NAME TEXT,
    GOST TEXT,
    SIZE TEXT,
    DATE_IN DATE,
    QUANTITY_IN TEXT,
    WEAROUT_IN TEXT,
    COST_IN TEXT,
    DATE_OUT DATE,
    QUANTITY_OUT TEXT,
    WEAROUT_OUT TEXT,
    COST_OUT TEXT,
    EXPIRATION_DATE DATE
);

CREATE TABLE WASHING_STANDARTS (
    ID SERIAL PRIMARY KEY,
    EMPLOYEE_ID INTEGER REFERENCES EMPLOYEE(ID),
    POSITION TEXT,
    NAME TEXT,
    MEASURE TEXT,
    QUANTITY_YEAR TEXT,
    QUANTITY_MONTH TEXT
);

CREATE TABLE WASHING_EQUIPMENT (
    ID SERIAL PRIMARY KEY,
    EMPLOYEE_ID INTEGER REFERENCES EMPLOYEE(ID),
    NAME TEXT,
    CERTIFICATE TEXT,
    DATE_IN DATE,
    QUANTITY_IN TEXT,
    ISSUING_METHOD TEXT,
    NEXT_ISSUING_DATE DATE
);